image: python:3.11-slim

stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  OMP_NUM_THREADS: "1"
  MKL_NUM_THREADS: "1"

cache:
  key:
    files:
      - requirements.txt
  paths:
    - .cache/pip

tests:
  stage: test
  before_script:
    - export PATH="/home/eid23/miniforge3/envs/p28_py311_env/bin:$PATH"
    - export PYTHONNOUSERSITE=1
  script:
    - python -m pytest -q
